# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chenyidong/multistageALM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chenyidong/multistageALM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/local/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/local/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenyidong/multistageALM/CMakeFiles /home/chenyidong/multistageALM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chenyidong/multistageALM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named ADMM_Solver

# Build rule for target.
ADMM_Solver: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 ADMM_Solver
.PHONY : ADMM_Solver

# fast build rule for target.
ADMM_Solver/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/build
.PHONY : ADMM_Solver/fast

#=============================================================================
# Target rules for targets named Common

# Build rule for target.
Common: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Common
.PHONY : Common

# fast build rule for target.
Common/fast:
	$(MAKE) $(MAKESILENT) -f Common/CMakeFiles/Common.dir/build.make Common/CMakeFiles/Common.dir/build
.PHONY : Common/fast

#=============================================================================
# Target rules for targets named Models

# Build rule for target.
Models: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Models
.PHONY : Models

# fast build rule for target.
Models/fast:
	$(MAKE) $(MAKESILENT) -f Common/Models/CMakeFiles/Models.dir/build.make Common/Models/CMakeFiles/Models.dir/build
.PHONY : Models/fast

cnicsparsematrix.o: cnicsparsematrix.cpp.o
.PHONY : cnicsparsematrix.o

# target to build an object file
cnicsparsematrix.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/cnicsparsematrix.cpp.o
.PHONY : cnicsparsematrix.cpp.o

cnicsparsematrix.i: cnicsparsematrix.cpp.i
.PHONY : cnicsparsematrix.i

# target to preprocess a source file
cnicsparsematrix.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/cnicsparsematrix.cpp.i
.PHONY : cnicsparsematrix.cpp.i

cnicsparsematrix.s: cnicsparsematrix.cpp.s
.PHONY : cnicsparsematrix.s

# target to generate assembly for a file
cnicsparsematrix.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/cnicsparsematrix.cpp.s
.PHONY : cnicsparsematrix.cpp.s

main_admm.o: main_admm.cpp.o
.PHONY : main_admm.o

# target to build an object file
main_admm.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/main_admm.cpp.o
.PHONY : main_admm.cpp.o

main_admm.i: main_admm.cpp.i
.PHONY : main_admm.i

# target to preprocess a source file
main_admm.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/main_admm.cpp.i
.PHONY : main_admm.cpp.i

main_admm.s: main_admm.cpp.s
.PHONY : main_admm.s

# target to generate assembly for a file
main_admm.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/ADMM_Solver.dir/build.make CMakeFiles/ADMM_Solver.dir/main_admm.cpp.s
.PHONY : main_admm.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... ADMM_Solver"
	@echo "... Common"
	@echo "... Models"
	@echo "... cnicsparsematrix.o"
	@echo "... cnicsparsematrix.i"
	@echo "... cnicsparsematrix.s"
	@echo "... main_admm.o"
	@echo "... main_admm.i"
	@echo "... main_admm.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

